language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - opam
    - ocaml-native-compilers
install: sh -ex .travis-install.sh
cache:
  directories:
  - ${HOME}/.local
  - ${HOME}/.opam
script: sh -ex .travis-ci.sh
env:
  - OCAML_VERSION=4.02.3
  - OCAML_VERSION=4.03.0
