language: c
sudo: true
dist: xenial
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: |
  bash -ex .travis-opam.sh
env:
  global:
  - EXTRA_DEPS="dot-merlin-reader"
  - PINS="dot-merlin-reader.dev:."
  matrix:
  - OCAML_VERSION=4.11
    PACKAGE=merlin
os:
  - linux
  - macos
  - freebsd
